from __future__ import annotations

import json
import csv
from collections import defaultdict
from datetime import datetime, timezone
from io import StringIO
from pathlib import Path
from typing import Any


def normalize_hex(value: Any) -> str:
    text = str(value or "")
    return "".join(char for char in text if char in "0123456789abcdefABCDEF").upper()


def dmm_game_file(match: dict[str, Any]) -> str:
    return str(
        match.get("archive_path")
        or match.get("relative_file")
        or match.get("file")
        or match.get("patch_skeleton", {}).get("file")
        or ""
    ).replace("\\", "/")


def dmm_offset(match: dict[str, Any]) -> int:
    value = match.get("decoded_offset", match.get("offset", match.get("patch_skeleton", {}).get("offset", 0)))
    try:
        return int(value or 0)
    except (TypeError, ValueError):
        return 0


def dmm_label(match: dict[str, Any]) -> str:
    evidence = str(match.get("evidence_value") or match.get("hit_text") or "candidate")
    confidence = match.get("confidence", "")
    match_type = str(match.get("match_type") or "unknown")
    if len(evidence) > 80:
        evidence = evidence[:77] + "..."
    return f"[CDSniffer] {match_type} {evidence} confidence={confidence}"


def build_dmm_patch_draft(
    result: dict[str, Any],
    *,
    title: str = "CDSniffer Patch Draft",
    version: str = "0.1.0",
    author: str = "CDSniffer",
    description: str | None = None,
    patched_placeholder: str = "",
) -> dict[str, Any]:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    skipped = 0
    for match in result.get("matches", []) or []:
        if not isinstance(match, dict):
            skipped += 1
            continue
        game_file = dmm_game_file(match)
        original = normalize_hex(match.get("original_bytes") or match.get("patch_skeleton", {}).get("original"))
        if not game_file or not original:
            skipped += 1
            continue
        grouped[game_file].append(
            {
                "offset": dmm_offset(match),
                "label": dmm_label(match),
                "original": original,
                "patched": patched_placeholder,
            }
        )

    modinfo_description = description or (
        "Generated by CDSniffer from correlation results. Review every offset and fill patched values before using in DMM."
    )
    return {
        "modinfo": {
            "title": title,
            "version": version,
            "author": author,
            "description": modinfo_description,
            "generated_by": "CDSniffer",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "source_capture": result.get("capture_path"),
            "warning": "Draft only: patched values are placeholders and must be reviewed before use.",
        },
        "patches": [
            {"game_file": game_file, "changes": sorted(changes, key=lambda item: int(item["offset"]))}
            for game_file, changes in sorted(grouped.items())
        ],
        "cdsniffer": {
            "schema": "dmm-patch-draft",
            "match_count": len(result.get("matches", []) or []),
            "exported_change_count": sum(len(changes) for changes in grouped.values()),
            "skipped_match_count": skipped,
            "source_result_type": "archive-correlation" if result.get("index_db") else "file-correlation",
        },
    }


def render_dmm_patch_draft(result: dict[str, Any], **kwargs: Any) -> str:
    return json.dumps(build_dmm_patch_draft(result, **kwargs), ensure_ascii=False, indent=2) + "\n"


def load_dmm_patch_json(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"DMM JSON must be an object: {path}")
    return data


def dmm_change_records(data: dict[str, Any], source_path: Path | str) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    source = str(source_path)
    title = str(data.get("modinfo", {}).get("title") or Path(source).stem)
    for patch in data.get("patches", []) or []:
        if not isinstance(patch, dict):
            continue
        game_file = str(patch.get("game_file") or patch.get("file") or "").replace("\\", "/")
        changes = patch.get("changes", []) if isinstance(patch.get("changes"), list) else [patch]
        for change in changes:
            if not isinstance(change, dict):
                continue
            offset = _int_or_none(change.get("offset"))
            original = normalize_hex(change.get("original") or change.get("original_bytes"))
            if not game_file or offset is None or not original:
                continue
            length = max(1, len(original) // 2)
            records.append(
                {
                    "source": source,
                    "title": title,
                    "game_file": game_file,
                    "offset": offset,
                    "offset_hex": f"0x{offset:X}",
                    "end": offset + length,
                    "end_hex": f"0x{offset + length:X}",
                    "length": length,
                    "original": original,
                    "patched": normalize_hex(change.get("patched")),
                    "label": str(change.get("label") or ""),
                }
            )
    return records


def build_dmm_conflict_report(candidate_path: Path, against_paths: list[Path]) -> dict[str, Any]:
    candidate_data = load_dmm_patch_json(candidate_path)
    candidate_records = dmm_change_records(candidate_data, candidate_path)
    against_records: list[dict[str, Any]] = []
    for path in against_paths:
        against_records.extend(dmm_change_records(load_dmm_patch_json(path), path))

    against_by_file = _group_dmm_records_by_file(against_records)
    candidate_by_file = _group_dmm_records_by_file(candidate_records)

    conflicts: list[dict[str, Any]] = []
    for candidate in candidate_records:
        for existing in against_by_file.get(_normalized_dmm_game_file(candidate), []):
            conflict = _dmm_overlap(candidate, existing)
            if conflict:
                conflicts.append(conflict)

    internal_conflicts: list[dict[str, Any]] = []
    for records in candidate_by_file.values():
        for index, left in enumerate(records):
            for right in records[index + 1 :]:
                conflict = _dmm_overlap(left, right)
                if conflict:
                    conflict["conflict_scope"] = "candidate-internal"
                    internal_conflicts.append(conflict)

    return {
        "schema": "dmm-conflict-report",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "candidate_path": str(candidate_path),
        "against_paths": [str(path) for path in against_paths],
        "candidate_change_count": len(candidate_records),
        "against_change_count": len(against_records),
        "conflict_count": len(conflicts),
        "internal_conflict_count": len(internal_conflicts),
        "has_conflicts": bool(conflicts or internal_conflicts),
        "conflicts": conflicts,
        "internal_conflicts": internal_conflicts,
    }


def render_dmm_conflict_csv(report: dict[str, Any]) -> str:
    rows = list(report.get("conflicts", [])) + list(report.get("internal_conflicts", []))
    buffer = StringIO()
    fieldnames = [
        "conflict_scope",
        "conflict_type",
        "game_file",
        "overlap_start_hex",
        "overlap_end_hex",
        "candidate_source",
        "candidate_offset_hex",
        "candidate_length",
        "existing_source",
        "existing_offset_hex",
        "existing_length",
    ]
    writer = csv.DictWriter(buffer, fieldnames=fieldnames)
    writer.writeheader()
    for row in rows:
        writer.writerow({key: row.get(key, "") for key in fieldnames})
    return buffer.getvalue()


def render_dmm_conflict_markdown(report: dict[str, Any]) -> str:
    rows = list(report.get("conflicts", [])) + list(report.get("internal_conflicts", []))
    lines = [
        "# CDSniffer DMM Conflict Report",
        "",
        f"- Candidate: `{report.get('candidate_path', '')}`",
        f"- Existing mods checked: `{len(report.get('against_paths', []))}`",
        f"- Candidate changes: `{report.get('candidate_change_count', 0)}`",
        f"- Existing changes: `{report.get('against_change_count', 0)}`",
        f"- Conflicts: `{report.get('conflict_count', 0)}`",
        f"- Internal conflicts: `{report.get('internal_conflict_count', 0)}`",
        "",
        "| Scope | Type | File | Overlap | Candidate | Existing |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    if not rows:
        lines.append("| - | - | - | - | No conflicts found | - |")
        return "\n".join(lines) + "\n"
    for row in rows:
        game_file = str(row.get("game_file", "")).replace("|", "\\|")
        overlap = f"`{row.get('overlap_start_hex')}`-`{row.get('overlap_end_hex')}`"
        candidate = f"`{row.get('candidate_source')}` @ `{row.get('candidate_offset_hex')}` ({row.get('candidate_length')} bytes)"
        existing = f"`{row.get('existing_source')}` @ `{row.get('existing_offset_hex')}` ({row.get('existing_length')} bytes)"
        lines.append(f"| {row.get('conflict_scope', '')} | {row.get('conflict_type', '')} | {game_file} | {overlap} | {candidate} | {existing} |")
    return "\n".join(lines) + "\n"


def _dmm_overlap(candidate: dict[str, Any], existing: dict[str, Any]) -> dict[str, Any] | None:
    if candidate["game_file"].lower() != existing["game_file"].lower():
        return None
    start = max(int(candidate["offset"]), int(existing["offset"]))
    end = min(int(candidate["end"]), int(existing["end"]))
    if start >= end:
        return None
    conflict_type = "exact" if candidate["offset"] == existing["offset"] and candidate["end"] == existing["end"] else "overlap"
    return {
        "conflict_scope": "against-existing",
        "conflict_type": conflict_type,
        "game_file": candidate["game_file"],
        "overlap_start": start,
        "overlap_start_hex": f"0x{start:X}",
        "overlap_end": end,
        "overlap_end_hex": f"0x{end:X}",
        "candidate_source": candidate["source"],
        "candidate_title": candidate["title"],
        "candidate_offset": candidate["offset"],
        "candidate_offset_hex": candidate["offset_hex"],
        "candidate_length": candidate["length"],
        "candidate_original": candidate["original"],
        "existing_source": existing["source"],
        "existing_title": existing["title"],
        "existing_offset": existing["offset"],
        "existing_offset_hex": existing["offset_hex"],
        "existing_length": existing["length"],
        "existing_original": existing["original"],
    }


def _normalized_dmm_game_file(record: dict[str, Any]) -> str:
    return str(record.get("game_file") or "").replace("\\", "/").lower()


def _group_dmm_records_by_file(records: list[dict[str, Any]]) -> dict[str, list[dict[str, Any]]]:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for record in records:
        grouped[_normalized_dmm_game_file(record)].append(record)
    return grouped


def _int_or_none(value: Any) -> int | None:
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def load_correlation_result(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("Correlation result must be a JSON object")
    if not isinstance(data.get("matches"), list):
        raise ValueError("Correlation result does not contain a matches array")
    return data
