from __future__ import annotations

import json
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def normalize_hex(value: Any) -> str:
    text = str(value or "")
    return "".join(char for char in text if char in "0123456789abcdefABCDEF").upper()


def dmm_game_file(match: dict[str, Any]) -> str:
    return str(
        match.get("archive_path")
        or match.get("relative_file")
        or match.get("file")
        or match.get("patch_skeleton", {}).get("file")
        or ""
    ).replace("\\", "/")


def dmm_offset(match: dict[str, Any]) -> int:
    value = match.get("decoded_offset", match.get("offset", match.get("patch_skeleton", {}).get("offset", 0)))
    try:
        return int(value or 0)
    except (TypeError, ValueError):
        return 0


def dmm_label(match: dict[str, Any]) -> str:
    evidence = str(match.get("evidence_value") or match.get("hit_text") or "candidate")
    confidence = match.get("confidence", "")
    match_type = str(match.get("match_type") or "unknown")
    if len(evidence) > 80:
        evidence = evidence[:77] + "..."
    return f"[CDSniffer] {match_type} {evidence} confidence={confidence}"


def build_dmm_patch_draft(
    result: dict[str, Any],
    *,
    title: str = "CDSniffer Patch Draft",
    version: str = "0.1.0",
    author: str = "CDSniffer",
    description: str | None = None,
    patched_placeholder: str = "",
) -> dict[str, Any]:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    skipped = 0
    for match in result.get("matches", []) or []:
        if not isinstance(match, dict):
            skipped += 1
            continue
        game_file = dmm_game_file(match)
        original = normalize_hex(match.get("original_bytes") or match.get("patch_skeleton", {}).get("original"))
        if not game_file or not original:
            skipped += 1
            continue
        grouped[game_file].append(
            {
                "offset": dmm_offset(match),
                "label": dmm_label(match),
                "original": original,
                "patched": patched_placeholder,
            }
        )

    modinfo_description = description or (
        "Generated by CDSniffer from correlation results. Review every offset and fill patched values before using in DMM."
    )
    return {
        "modinfo": {
            "title": title,
            "version": version,
            "author": author,
            "description": modinfo_description,
            "generated_by": "CDSniffer",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "source_capture": result.get("capture_path"),
            "warning": "Draft only: patched values are placeholders and must be reviewed before use.",
        },
        "patches": [
            {"game_file": game_file, "changes": sorted(changes, key=lambda item: int(item["offset"]))}
            for game_file, changes in sorted(grouped.items())
        ],
        "cdsniffer": {
            "schema": "dmm-patch-draft",
            "match_count": len(result.get("matches", []) or []),
            "exported_change_count": sum(len(changes) for changes in grouped.values()),
            "skipped_match_count": skipped,
            "source_result_type": "archive-correlation" if result.get("index_db") else "file-correlation",
        },
    }


def render_dmm_patch_draft(result: dict[str, Any], **kwargs: Any) -> str:
    return json.dumps(build_dmm_patch_draft(result, **kwargs), ensure_ascii=False, indent=2) + "\n"


def load_correlation_result(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("Correlation result must be a JSON object")
    if not isinstance(data.get("matches"), list):
        raise ValueError("Correlation result does not contain a matches array")
    return data
